/*
 * Dio_Cfg.c
 *
 * Created: 7/13/2021 7:55:09 PM
 *  Author: Ahmed Nabil
 */ 

#include "Dio_LCfg.h"
#include "Dio.h"

strDio_Config_t strDio_pins[DIO_USED_PINS_NUM]=
{
	{DioConf_LCD_RS_PORT_NUM, DioConf_LCD_RS_PIN_NUM, DIO_PIN_DIR_OUTPUT, PIN_LOW},
	{DioConf_LCD_RW_PORT_NUM, DioConf_LCD_RW_PIN_NUM, DIO_PIN_DIR_OUTPUT, PIN_LOW},
	{DioConf_LCD_E_PORT_NUM, DioConf_LCD_E_PIN_NUM, DIO_PIN_DIR_OUTPUT, PIN_LOW},
	{DioConf_LCD_D4_PORT_NUM, DioConf_LCD_D4_PIN_NUM, DIO_PIN_DIR_OUTPUT, PIN_LOW},
	{DioConf_LCD_D5_PORT_NUM, DioConf_LCD_D5_PIN_NUM, DIO_PIN_DIR_OUTPUT, PIN_LOW},
	{DioConf_LCD_D6_PORT_NUM, DioConf_LCD_D6_PIN_NUM, DIO_PIN_DIR_OUTPUT, PIN_LOW},
	{DioConf_LCD_D7_PORT_NUM, DioConf_LCD_D7_PIN_NUM, DIO_PIN_DIR_OUTPUT, PIN_LOW},
	{DioConf_IN1_D2_PORT_NUM, DioConf_IN1_D2_PIN_NUM, DIO_PIN_DIR_OUTPUT, PIN_LOW},
	{DioConf_IN2_D3_PORT_NUM, DioConf_IN2_D3_PIN_NUM, DIO_PIN_DIR_OUTPUT, PIN_LOW},
	{DioConf_PWM_D4_PORT_NUM, DioConf_PWM_D4_PIN_NUM, DIO_PIN_DIR_OUTPUT, PIN_LOW},
	{DioConf_IN3_D6_PORT_NUM, DioConf_IN3_D6_PIN_NUM, DIO_PIN_DIR_OUTPUT, PIN_LOW},
	{DioConf_IN4_D7_PORT_NUM, DioConf_IN4_D7_PIN_NUM, DIO_PIN_DIR_OUTPUT, PIN_LOW},
	{DioConf_BTN0_C4_PORT_NUM, DioConf_BTN0_C4_PIN_NUM, DIO_PIN_DIR_INPUT, PIN_PDR},
	{DioConf_US_TRG_PORT_NUM, DioConf_US_TRG_PIN_NUM, DIO_PIN_DIR_OUTPUT, PIN_LOW}
};

